AppCoder/urls.py
from django.urls import path

from AppCoder import views

from django.contrib.auth.views import LogoutView

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
   
    path('', views.inicio, name="inicio"), 
    
    path('colaboradores', views.colaboradores, name="colaboradores"),
    path('colaborador/create/', views.Crear_colaborador, name="colaborador-create"),
    path('eliminarColaborador/<str:colaborador_nombre>/', views.eliminnar_colaborador, name="eliminar-colaborador"),
    path('editarColaborador/<str:colaborador_nombre>/', views.editar_colaborador, name="editar-colaborador"),
    
    path('certificados', views.certificados, name="certificados"),
    path('certificado/create/', views.crear_certificado, name="certificado-create"),
    path('eliminarCertificado/<str:certificado_nombre>/', views.eliminnar_certificado, name="eliminar-certificado"),
    path('editarCertificado/<str:certificado_nombre>/', views.editar_certificado, name="editar-certificado"),
    
    path('login/', views.login_request, name="login"),
    path('registro/', views.registro, name="registro"),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name="logout"),
    path('editarPerfil/', views.editarPerfil, name="EditarPerfil"),
    path('cambiarContrasenia/',views.CambiarContrasenia.as_view() , name="CambiarContrasenia"),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PlaygrounFinalProjectArrambide/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppCoder/',include(('AppCoder.urls','AppCoder'), namespace='AppCoder'))
]

AppCoder/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from django.utils import timezone

class Colaborador(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.EmailField()
    Cargo = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='colaborador_imagenes/',null=True,blank=True)
    def __str__(self):
        return  f" Nombre: {self.nombre} - Apellido: {self.apellido} - Email: {self.email} - cargo: {self.Cargo}"


class Certificado(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    fecha_entrega = models.DateField()
    imagen = models.ImageField(upload_to='certificados_imagenes/', null=True, blank=True)
    colaborador = models.ForeignKey(Colaborador, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f" Nombre: {self.nombre} - Fecha Entrega: {self.fecha_entrega}"
    

class Avatar(models.Model):
    user =  models.OneToOneField(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank=True)
    def __str__(self):
        return f"{self.user} - {self.imagen}"

AppCoder/forms.py
from django import forms
from .models import  Certificado, Colaborador, User
from django.contrib.auth.forms import  UserCreationForm, UserChangeForm

class CertificadoForm(forms.ModelForm):
    class Meta:
        model= Certificado
        fields = '__all__'

class ColaboradorForm(forms.ModelForm):
    class Meta:
        model= Colaborador
        fields = '__all__'

class UserCreationFormCustom(UserCreationForm):
    username = forms.CharField(label='Usuario')
    email = forms.EmailField(label="E-mail")
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
    first_name = forms.CharField(label= "Nombre")
    last_name = forms.CharField(label= "Apellido")
    class Meta:
        model = User
        fields = ['username','email','password1','password2','first_name','last_name']
        help_texts = {k:"" for k in fields}

class UserEditForm(UserChangeForm):

    password=None
    email = forms.EmailField(label="Ingrese su email:")
    last_name = forms.CharField(label="Apellido")
    first_name = forms.CharField(label="Nombre")
    imagen = forms.ImageField(label="Avatar", required=False)

    class Meta:
        model = User
        fields = ['email','last_name','first_name','imagen']

AppCoder/views.py
from django.shortcuts import render, redirect
from django.template import Template, Context
from django.http import HttpResponse
from .models import Certificado, Colaborador, User
from .forms import ColaboradorForm, CertificadoForm, UserCreationFormCustom, UserEditForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit  import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.forms import  AuthenticationForm, UserCreationForm
from django.contrib.auth import login, authenticate
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin



def index(request):
    return render(request,'index.html')

def inicio(request):
    return render(request, 'inicio.html')

#Colaboradores 

@login_required
def colaboradores(request):
    colaboradores = Colaborador.objects.all()
    return render(request, 'colaborador.html',{'colaboradores':colaboradores})



@login_required
def Crear_colaborador(request):
    if request.method == 'POST':
        form = ColaboradorForm(request.POST, request.FILES)
        if form.is_valid():
            colaborador = form.save(commit=False)  
            if 'imagen' in request.FILES:
                colaborador.imagen = request.FILES['imagen']  
            colaborador.save()  
            return redirect('AppCoder:colaboradores')
    else:
        form = ColaboradorForm()
    return render(request, 'colaborador_form.html', {'form': form})

@login_required
def eliminnar_colaborador(request,colaborador_nombre):
    colaborador = Colaborador.objects.get(nombre=colaborador_nombre)
    colaborador.delete()

    colaboradores = Colaborador.objects.all()
    return render(request, 'colaborador.html',{'colaboradores':colaboradores})
@login_required
def editar_colaborador(request,colaborador_nombre):
    colaborador = Colaborador.objects.get(nombre=colaborador_nombre)
    if request.method == 'POST':
        miFormulario = ColaboradorForm(request.POST)
        print(miFormulario)
        if miFormulario.is_valid():
            informacion = miFormulario.cleaned_data
            colaborador.nombre = informacion['nombre']
            colaborador.apellido = informacion['apellido']
            colaborador.email = informacion['email']
            colaborador.Cargo = informacion['Cargo']
            colaborador.save()
            return redirect('AppCoder:colaboradores')
    else:
        miFormulario = ColaboradorForm(initial={'nombre':colaborador.nombre,'apellido':colaborador.apellido,
                                             'email': colaborador.email, 'Cargo': colaborador.Cargo})
    return render(request, "editarColaborador.html",{"miFormulario":miFormulario, "colaborador_nombre": colaborador_nombre})

# CERTIFICADO

from django.contrib.auth.decorators import login_required

@login_required
def crear_certificado(request):
    if request.method == 'POST':
        form = CertificadoForm(request.POST, request.FILES)
        if form.is_valid():
            certificado = form.save(commit=False)
            if 'imagen' in request.FILES:
                certificado.imagen = request.FILES['imagen']
            certificado.usuario = request.user
            certificado.save()
            return redirect('AppCoder:certificados')
    else:
        form = CertificadoForm()
    return render(request, 'certificado_form.html', {'form': form})



@login_required
def certificados(request):
    certificado = Certificado.objects.all()
    return render(request, 'certificados.html',{'certificados':certificado})
@login_required
def eliminnar_certificado(request,certificado_nombre):
    certificado = Certificado.objects.get(nombre=certificado_nombre)
    certificado.delete()

    certificado = Certificado.objects.all()
    return render(request, 'certificados.html',{'certificados':certificados})
@login_required
def editar_certificado(request,certificado_nombre):
    certificado= Certificado.objects.get(nombre=certificado_nombre)
    if request.method == 'POST':
        miFormulario = CertificadoForm(request.POST)
        print(miFormulario)
        if miFormulario.is_valid():
            informacion = miFormulario.cleaned_data
            certificado.nombre = informacion['nombre']
            certificado.fecha_entrega = informacion['fecha_entrega']
            certificado.entregado = informacion['entregado']
            
            certificado.save()
            return render(request,"inicio.html")
    else:
        miFormulario = CertificadoForm(initial={'nombre':certificado.nombre,'Fecha Entrega':certificado.fecha_entrega})
    return render(request, "editarcertificado.html",{"miFormulario":miFormulario, "certificado_nombre": certificado_nombre})
  
  # LOGIN - LOGIN - LOGIN - LOGIN - LOGIN - LOGIN - LOGIN - LOGIN - LOGIN - LOGIN - 

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm( request, data=request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contrasenia = form.cleaned_data.get('password')
            user = authenticate(username= usuario, password=contrasenia)
            login(request, user)
            return render(request, "inicio.html", {"mensaje": f'Bienvenido {user.username}'})
    else:
        form = AuthenticationForm()
    return render(request, "login.html",{"form": form})

def registro(request):
    if request.method == 'POST':
        form = UserCreationFormCustom(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            form.save()  
            return render(request, 'inicio.html', {"mensaje": "Usuario Creado"})
    else:
        form = UserCreationFormCustom()
    return render(request, "registro.html", {"form": form})

def editarPerfil(request):
    usuario = request.user
    if request.method == 'POST':
        miFormulario = UserEditForm(request.POST, request.FILES, instance=request.user)

        if miFormulario.is_valid():
                if miFormulario.cleaned_data.get('imagen'):
                    usuario.avatar.imagen = miFormulario.cleaned_data.get('imagen')
                    usuario.avatar.save()

                miFormulario.save()

                return render(request, "registro.html")
    else:
        miFormulario = UserEditForm(initial={'imagen': usuario.avatar.imagen}, instance=request.user)
        return render(request, "editarPerfil.html", {"miFormulario": miFormulario, "usuario": usuario})

    
class CambiarContrasenia(LoginRequiredMixin, PasswordChangeView):
    template_name = 'cambiar_contrasenia.html'
    success_url = reverse_lazy('EditarPerfil')

AppCoder/templates/cambiar_contrasenia.html
{% extends 'padre.html' %}

{% load static %}


{% block contenidoQueCambia %}

    <h1>Cambiar Contraseña </h1>
    <h6>de Usuario</h6>
 

    <form action="" method="POST"> {% csrf_token %}
        <table>
            {{ form}}
        </table>
        <button>Cambiar</button>
    </form>
{% endblock contenidoQueCambia %}

AppCoder/templates/certificado_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>

        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />

        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />

        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'AppCoder:inicio' %}" style="color: red;">Inicio</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:colaboradores' %}" style="color: blue">Colaboradores</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:certificados' %}" style="color: blue">Certificados</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:logout' %}">LOGOUT</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:EditarPerfil' %}">{{request.user.username}}</a>
                    {%if request.user.avatar %}
                    <img src ="{{request.user.avatar.imagen.url}}" alt="" height="40px"
                    {% endif %}
                {% else %}
                    <a class="btn btn-primary" href="{% url 'AppCoder:inicio' %}" style="color: white;">Inicio</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:login' %}">LOGIN</a>
                    
                {% endif %}
            </div>
        </nav>
    
        {% block contenidoQueCambia %}
        
                <h1>Cargar un Nuevo Certificado</h1>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Guardar</button>
                </form>

        {% endblock contenidoQueCambia %}


        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    </body>
</html>

AppCoder/templates/certificados.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>

        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />

        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />

        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'AppCoder:inicio' %}" style="color: red;">Inicio</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:colaboradores' %}" style="color: blue">Colaboradores</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:certificados' %}" style="color: blue">Certificados</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:logout' %}">LOGOUT</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:EditarPerfil' %}">{{request.user.username}}</a>
                    {%if request.user.avatar %}
                    <img src ="{{request.user.avatar.imagen.url}}" alt="" height="40px"
                    {% endif %}
                {% else %}
                    <a class="btn btn-primary" href="{% url 'AppCoder:inicio' %}" style="color: white;">Inicio</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:login' %}">LOGIN</a>
                    
                {% endif %}
            </div>
        </nav>
{% block contenidoQueCambia %}
<h1>Lista de Certificados</h1>
<div class="container position-relative">
    <body>
         <a href="{% url 'AppCoder:certificado-create' %}">Ingresar NUEVO Certificado</a> 
    </body>
</div>
<br>

<ul>
    {% for certificado in certificados %}
        <li>
            Tipo Cerficado: {{ certificado.nombre }}, Fecha: {{ certificado.fecha_entrega }} <br> Motivo: {{ certificado.descripcion }} 
            <br> Colaborador: {{ certificado.colaborador.nombre }}  {{ certificado.colaborador.apellido }} -  {{ certificado.colaborador.Cargo }}
            <br> Cargado por el Usuario: {{ certificado.usuario.username }} {{ certificado.usuario.last_name }}
            <br>
            {% if certificado.imagen %}
                <img src="{{  certificado.imagen.url }}">
            {% endif %}
            <br>
            <a href="{% url 'AppCoder:eliminar-certificado' certificado.nombre %}">
                <button>Eliminar</button>
            </a>
            <a href="{% url 'AppCoder:editar-certificado' certificado.nombre %}">
                <button>Editar</button>
            </a>
        </li>
    {% endfor %}
</ul>

{% endblock contenidoQueCambia %}

AppCoder/templates/colaborador.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>

        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />

        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />

        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'AppCoder:inicio' %}" style="color: red;">Inicio</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:colaboradores' %}" style="color: blue">Colaboradores</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:certificados' %}" style="color: blue">Certificados</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:logout' %}">LOGOUT</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:EditarPerfil' %}">{{request.user.username}}</a>
                    {%if request.user.avatar %}
                    <img src ="{{request.user.avatar.imagen.url}}" alt="" height="40px"
                    {% endif %}
                {% else %}
                    <a class="btn btn-primary" href="{% url 'AppCoder:inicio' %}" style="color: white;">Inicio</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:login' %}">LOGIN</a>
                    
                {% endif %}
            </div>
        </nav>
    
        {% block contenidoQueCambia %}
                <h1>Listado de Colaboradores</h1>
                <ul>
                    {% for colaborador in colaboradores %}
                        <li>
                            {{ colaborador.nombre }} , {{ colaborador.apellido }} , {{ colaborador.Cargo }} , {{ colaborador.email }}
                            
                            {% if colaborador.imagen %}
                                <img src="{{ Colaborador.imagen.url }}" width="100" height="100">  
                            {% endif %}

                            <a href="{% url 'AppCoder:eliminar-colaborador' colaborador.nombre %}">
                                <button>Eliminar</button>
                            </a>
                            <a href="{% url 'AppCoder:editar-colaborador' colaborador.nombre %}">
                                <button>Editar</button>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            
                <a href="{% url 'AppCoder:colaborador-create' %}">Crear un nuevo Colaborador</a> 
        {% endblock contenidoQueCambia %}



        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    </body>
</html>

AppCoder/templates/colaborador_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>

        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />

        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />

        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'AppCoder:inicio' %}" style="color: red;">Inicio</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:colaboradores' %}" style="color: blue">Colaboradores</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:certificados' %}" style="color: blue">Certificados</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:logout' %}">LOGOUT</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:EditarPerfil' %}">{{request.user.username}}</a>
                    {%if request.user.avatar %}
                    <img src ="{{request.user.avatar.imagen.url}}" alt="" height="40px"
                    {% endif %}
                {% else %}
                    <a class="btn btn-primary" href="{% url 'AppCoder:inicio' %}" style="color: white;">Inicio</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:login' %}">LOGIN</a>
                    
                {% endif %}
            </div>
        </nav>
    
        {% block contenidoQueCambia %}
        
                <h1>Crear un Nuevo Colaborador</h1>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Guardar</button>
                </form>

        {% endblock contenidoQueCambia %}


        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    </body>
</html>

AppCoder/templates/editarColaborador.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>

        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />

        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />

        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'AppCoder:inicio' %}" style="color: red;">Inicio</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:colaboradores' %}" style="color: blue">Colaboradores</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:certificados' %}" style="color: blue">Certificados</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:logout' %}">LOGOUT</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:EditarPerfil' %}">{{request.user.username}}</a>
                    {%if request.user.avatar %}
                    <img src ="{{request.user.avatar.imagen.url}}" alt="" height="40px"/>
                    {% endif %}
                {% else %}
                    <a class="btn btn-primary" href="{% url 'AppCoder:inicio' %}" style="color: white;">Inicio</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:login' %}">LOGIN</a>
                    
                {% endif %}
            </div>
        </nav>


{% block contenidoQueCambia %}

    <h1>Editar Colaborador</h1>
    
    {% if miFormulario.errors %}
    <p style="color: red"> Etan mal los datos, revisar</p>
    {% endif %}

    <form action="" method="POST"> {% csrf_token %}
        <table>

            {{ miFormulario.as_table}}
        </table>
        
        <input type="submit", value="Enviar">
    </form>
{% endblock contenidoQueCambia %}

AppCoder/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>

        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />

        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />

        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />

        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                {% if user.is_authenticated %}
                    <a class="navbar-brand" href="{% url 'AppCoder:inicio' %}" style="color: red;">Inicio</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:colaboradores' %}" style="color: blue">Colaboradores</a>
                    <a class="navbar-brand" href="{% url 'AppCoder:certificados' %}" style="color: blue">Certificados</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:logout' %}">LOGOUT</a>
                    <a class="btn btn-primary" href="{% url 'AppCoder:EditarPerfil' %}">{{request.user.username}}</a>
                    {%if request.user.avatar %}
                    <img src ="{{request.user.avatar.imagen.url}}" alt="" height="40px"
                    {% endif %}
                {% else %}
                    <a class="btn btn-primary" href="{% url 'AppCoder:inicio' %}" style="color: white;">Inicio</a>

                    
                {% endif %}
            </div>
        </nav>
    
{% block contenidoQueCambia %}


<div class="login-container">
    <h1>Login</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Iniciar sesión</button>
    </form>

    <p>Si no tienes una cuenta, regístrate <a href="{% url 'AppCoder:registro' %}">aquí</a>.</p>
</div>

        {% endblock contenidoQueCambia %}


        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="js/scripts.js"></script>
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    </body>
</html>